/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package es.perelluent.tubify;

/**
 *
 * @author Perelluent
 */
public class AboutDialog extends javax.swing.JDialog {
    

    /**
     * Creates new form AboutDialog
     * @param parent
     * @param modal
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaAboutText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        txaAboutText.setEditable(false);
        txaAboutText.setColumns(1);
        txaAboutText.setRows(1);
        txaAboutText.setTabSize(1);
        txaAboutText.setText("Tubify\n\nAutor: Pere Garcias\n\nCourse: Desarrollo de Interfaces - DAM\n\nResources: \n- yt-dlp\n- ffmpeg\n\nRepo: https://github.com/Perelluent/Tubify.git");
        txaAboutText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txaAboutText.setMaximumSize(null);
        txaAboutText.setMinimumSize(new java.awt.Dimension(600, 600));
        txaAboutText.setPreferredSize(new java.awt.Dimension(300, 200));
        txaAboutText.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txaAboutText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 50, 340, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaAboutText;
    // End of variables declaration//GEN-END:variables
}
