/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.perelluent.tubify;

import java.awt.Color;

/**
 *
 * @author morda
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItsAboutPanel
     */
    public AboutPanel() {
        setBackground(Color.BLACK);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaAboutText = new javax.swing.JTextArea();

        txaAboutText.setEditable(false);
        txaAboutText.setColumns(1);
        txaAboutText.setRows(1);
        txaAboutText.setTabSize(1);
        txaAboutText.setText("Tubify\n\nAutor: Pere Garcias\n\nCourse: Desarrollo de Interfaces - DAM\n\nResources: \n- yt-dlp\n- ffmpeg\n\nRepo: https://github.com/Perelluent/Tubify.git");
        txaAboutText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txaAboutText.setMaximumSize(null);
        txaAboutText.setMinimumSize(new java.awt.Dimension(600, 600));
        txaAboutText.setPreferredSize(new java.awt.Dimension(300, 200));
        txaAboutText.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txaAboutText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaAboutText;
    // End of variables declaration//GEN-END:variables
}
