/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.perelluent.tubify;

import es.perelluent.mediapollingbean.dto.Media;
import es.perelluent.tubify.dto.LibraryTableModel;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URI;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author morda
 */
public class LibraryPanel extends javax.swing.JPanel {

    private final MainWindow main;
    private LibraryTableModel libraryModel;
    private TableRowSorter<LibraryTableModel> sorter;
    /**
     * Creates new form LibraryPanel
     *
     * @param main
     */
    public LibraryPanel(MainWindow main) {
        this.main = main;

        this.setLayout(new BorderLayout());
        
        initComponents();
        
        libraryModel = new LibraryTableModel();
        tblLibrary.setModel(libraryModel);
        
        this.add(jScrollPane1, BorderLayout.CENTER);
        
        sorter = new TableRowSorter<>(libraryModel);
        tblLibrary.setRowSorter(sorter);
        
        cmbFilter.addItem(new FilterCategory("Show All", ""));
        cmbFilter.addItem(new FilterCategory("Videos Only", "video"));
        cmbFilter.addItem(new FilterCategory("Audio Only", "audio"));
        
        cmbFilter.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FilterCategory selected = (FilterCategory) cmbFilter.getSelectedItem();
                filterTable(selected.getFilterValue());
            }
            
        });
        
        btnDelete.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDeleteActionPerformed(e);
            }
            
        });
    }
    
    public void loadMedia() {

        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try{
                    if (main.getMediaPollingBean().getToken() == null) {
                        System.out.println("Token error. You're not logged in");
                        return;
                    }
                    final List<Media> cloudFiles = main.getMediaPollingBean().getAllMedia();
                    SwingUtilities.invokeLater(() -> {
                    libraryModel.setMediaList(cloudFiles);
                });
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        });
        thread.start();
    } 

    private void filterTable(String query) {
        if (query.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query, 2));
        }
    }
    class FilterCategory {

        private final String displayName;
        private final String FilterValue;

        public FilterCategory(String displayName, String FilterValue) {
            this.displayName = displayName;
            this.FilterValue = FilterValue;
        }

        public String getFilterValue() {
            return FilterValue;
        }

        @Override
        public String toString() {
            return displayName;
        }

    }
    public void showNewMediaList(List<Media> newFiles) {
        if (newFiles == null || newFiles.isEmpty()) {
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrary = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        lblFilter = new javax.swing.JLabel();
        lblMediaLibrary = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();
        btnPlay = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 700));
        setLayout(null);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(730, 50, 72, 23);

        tblLibrary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibrary);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 790, 450);

        btnDelete.setText("Delete File");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(10, 560, 110, 23);

        lblFilter.setText("Filter");
        add(lblFilter);
        lblFilter.setBounds(20, 20, 41, 16);

        lblMediaLibrary.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        lblMediaLibrary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMediaLibrary.setText("MEDIA LIBRARY");
        add(lblMediaLibrary);
        lblMediaLibrary.setBounds(260, 30, 290, 40);

        add(cmbFilter);
        cmbFilter.setBounds(20, 50, 170, 22);

        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        add(btnPlay);
        btnPlay.setBounds(720, 550, 75, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        main.showMainWindow();
        main.repaint();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int viewRow = tblLibrary.getSelectedRow();
        if (viewRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a file to delete.");
            return;
        }

        int modelRow = tblLibrary.convertRowIndexToModel(viewRow);
        Media fileToDelete = libraryModel.getMediaAt(modelRow);

        int choice = JOptionPane.showConfirmDialog(this,
                "Remove '" + fileToDelete.mediaFileName + "' from list?\n(Note: API delete not supported yet)",
                "Confirm", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            // Nota: El ApiClient proporcionado NO tiene método delete. 
            // Solo lo quitamos de la vista visual.
            libraryModel.removeMedia(modelRow);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        int viewRow = tblLibrary.getSelectedRow();
        if (viewRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a file to play.");
            return;
        }
        int modelRow = tblLibrary.convertRowIndexToModel(viewRow);
        Media selectedMedia = libraryModel.getMediaAt(modelRow);

        if (selectedMedia != null && selectedMedia.blobUrl != null) {
            try {

                Desktop.getDesktop().browse(new URI(selectedMedia.blobUrl));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error opening URL: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid media URL.");
        }
    
    }//GEN-LAST:event_btnPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPlay;
    private javax.swing.JComboBox<FilterCategory> cmbFilter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblMediaLibrary;
    private javax.swing.JTable tblLibrary;
    // End of variables declaration//GEN-END:variables
}
