/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.perelluent.tubify;

import es.perelluent.tubify.dto.DownloadedFile;
import es.perelluent.tubify.dto.LibraryTableModel;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author morda
 */
public class LibraryPanel extends javax.swing.JPanel {

    private final MainWindow main;
    private LibraryTableModel library;

    /**
     * Creates new form LibraryPanel
     *
     * @param main
     */
    public LibraryPanel(MainWindow main) {
        this.main = main;

        initComponents();
        setBounds(0, 0, 900, 900);

        cmbFilter.addItem(new FilterCategory("Show All", ""));
        cmbFilter.addItem(new FilterCategory("Videos Only", "video"));
        cmbFilter.addItem(new FilterCategory("Audio Only", "audio"));
        
        cmbFilter.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FilterCategory selected = (FilterCategory) cmbFilter.getSelectedItem();
                if (library != null) {
                    library.filterByType(selected.getFilterValue());
                }
            }
            
        });
        
        btnDelete.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDeleteActionPerformed(e);
            }
            
        });
    }

    public void setModelLibrary(DefaultListModel<DownloadedFile> libraryModel) {

        LibraryTableModel ltb = new LibraryTableModel(libraryModel);
        this.library = new LibraryTableModel(libraryModel);
        tblLibrary.setModel(library);
        TableRowSorter<LibraryTableModel> sorter = new TableRowSorter<>(library);
        tblLibrary.setRowSorter(sorter);
    }

    class FilterCategory {

        private final String displayName;
        private final String FilterValue;

        public FilterCategory(String displayName, String FilterValue) {
            this.displayName = displayName;
            this.FilterValue = FilterValue;
        }

        public String getFilterValue() {
            return FilterValue;
        }

        @Override
        public String toString() {
            return displayName;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrary = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        lblFilter = new javax.swing.JLabel();
        lblMediaLibrary = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();
        btnPlay = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 700));
        setLayout(null);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(730, 50, 72, 23);

        tblLibrary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibrary);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 790, 290);

        btnDelete.setText("Delete File");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(10, 410, 110, 23);

        lblFilter.setText("Filter");
        add(lblFilter);
        lblFilter.setBounds(20, 20, 41, 16);

        lblMediaLibrary.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        lblMediaLibrary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMediaLibrary.setText("MEDIA LIBRARY");
        add(lblMediaLibrary);
        lblMediaLibrary.setBounds(260, 30, 290, 40);

        add(cmbFilter);
        cmbFilter.setBounds(20, 50, 72, 22);

        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        add(btnPlay);
        btnPlay.setBounds(720, 400, 75, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        main.showMainWindow();
        main.repaint();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int viewRow = tblLibrary.getSelectedRow();

    if (viewRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a file to delete.", "No file selected", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    int modelRow = tblLibrary.convertRowIndexToModel(viewRow);

    DownloadedFile fileToDelete = library.getFileAt(modelRow);

    if (fileToDelete == null) return;

    int choice = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to delete this file from your disk?\n" + fileToDelete.getFileName(), 
            "Confirm Deletion", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE);

    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        fileToDelete.deleteFromDisk();
        library.removeFile(fileToDelete);
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        int viewRow = tblLibrary.getSelectedRow();
        DownloadedFile selectedFile = library.getFileAt(viewRow);

        if (selectedFile == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a file from the list to play.",
                    "No file selected",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String filePath = selectedFile.getFilePath();
        if (filePath == null || filePath.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "File data is corrupt (no path).",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            File fileToOpen = new File(filePath);

            if (Desktop.isDesktopSupported() && fileToOpen.exists()) {
                Desktop.getDesktop().open(fileToOpen);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Cannot open the file. It may have been moved or deleted.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "An error occurred while trying to open the file:\n" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPlay;
    private javax.swing.JComboBox<FilterCategory> cmbFilter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblMediaLibrary;
    private javax.swing.JTable tblLibrary;
    // End of variables declaration//GEN-END:variables
}
