/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.perelluent.tubify;

/**
 *
 * @author Perelluent
 */
public class Preferences extends javax.swing.JPanel {
    private MainWindow main;
    /**
     * Creates new form Preferences
     */
    public Preferences(MainWindow main) {
        
        this.main = main;
        initComponents();
        
        setBounds(0, 0, 900, 900);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPreferences = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 900));
        setLayout(null);

        lblPreferences.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreferences.setText("Preferences");
        add(lblPreferences);
        lblPreferences.setBounds(114, 31, 170, 16);

        btnBack.setText("Back");
        btnBack.setName(""); // NOI18N
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(160, 120, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        main.showMainWindow();
        main.repaint();
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblPreferences;
    // End of variables declaration//GEN-END:variables
}
